name: test

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up rye
        uses: zztkm/setup-rye@use-uv
        with:
          use-uv: 'true'
      - name: Install dependencies
        run: rye sync --no-lock
      - name: Run tests
        run: |
          rye run pytest -ra --cov=src --cov-report=term --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}